

class FooError(Exception):
    """The FooError means that problem"""
    pass


class FooError(Exception):
    """The FooError means that problem"""


class FooError(Exception):
    5


'foo'

5

...

1234.5
